version: '3.9'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules

  api:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      REDIS_URL: redis://redis:6379/0
      WORKER_BROKER_URL: redis://redis:6379/0
      WORKER_RESULT_BACKEND: redis://redis:6379/1
      WORKER_URL: http://worker:8000
      STORAGE_DIR: /storage
    depends_on:
      - redis
    volumes:
      - ./server:/app
      - ./storage:/storage
      - /app/node_modules

  worker:
    build: ./worker
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
      - STORAGE_DIR=/storage
    depends_on:
      - redis
    volumes:
      - ./worker:/app
      - ./storage:/storage

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
