services:
  - type: web
    name: rap-tool-api
    env: docker
    autoDeploy: true
    plan: free
    region: oregon
    rootDir: server
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: STORAGE_DIR
        value: /data/storage
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
